version: '3.8'

services:
  app:
    build: .
    container_name: techable-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    depends_on:
      - redis
    command: ["npx", "ts-node", "src/server.ts"]

  redis:
    image: redis:latest
    container_name: techable-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
