version: "3.8"

services:
  app:
    build: .
    container_name: techable-app
    ports:
      - "3000:8080"
    environment:
      # TODO: environment variables and secrets shouldn't be here!!
      - TEACHABLE_API_BASE_URL=https://developers.teachable.com
      - TEACHABLE_API_KEY=7JbSA3ep6XOMV3t8t7QXuXq9HS79Dwnr
    volumes:
      - .:/app
    depends_on:
      - redis
    command: ["npx", "ts-node", "src/server.ts"]

  redis:
    image: redis:latest
    container_name: techable-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
