version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TEACHABLE_API_BASE_URL=https://developers.teachable.com
      - TEACHABLE_API_KEY=7JbSA3ep6XOMV3t8t7QXuXq9HS79Dwnr
      - SERVER_PORT=8080
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge